services:
  kafka:
    image: 'bitnami/kafka:3.3'
    ports:
      - '9096:9096'
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:SASL_PLAINTEXT
      - KAFKA_CFG_LISTENERS=EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://localhost:9096
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CLIENT_USER=kafkauser
      - KAFKA_CLIENT_PASSWORD=kafkapassword
      - KAFKA_CLIENT_USERS=kafkauser
      - KAFKA_CLIENT_PASSWORDS=kafkapassword
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper

  mongo:
    image: mongo:7.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  zookeeper:
    image: 'bitnami/zookeeper:3.7'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_USERS=kafkauser
      - ZOO_SERVER_PASSWORDS=kafkapassword
